// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project - AirWear UI draft 1

#ifndef _SQUARELINE_PROJECT___AIRWEAR_UI_DRAFT_1_UI_H
#define _SQUARELINE_PROJECT___AIRWEAR_UI_DRAFT_1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen3.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_background_img_w_gradient_png);    // assets/background_img_w_gradient.png
LV_IMG_DECLARE(ui_img_gauge_empty_png);    // assets/gauge_empty.png
LV_IMG_DECLARE(ui_img_gauge_full_png);    // assets/gauge_full.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
